# Generated by Django 5.2.6 on 2025-09-27 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradinguser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
