# Generated by Django 5.2.6 on 2025-10-09 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0002_tradinguser_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradinguser',
            name='leverage',
            field=models.IntegerField(default=1),
        ),
    ]
