# Generated by Django 5.2.6 on 2025-11-20 23:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0003_tradinguser_leverage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='tradinguser',
            old_name='testnet',
            new_name='demo',
        ),
        migrations.RemoveField(
            model_name='tradinguser',
            name='leverage',
        ),
        migrations.CreateModel(
            name='Leverages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20)),
                ('leverage', models.IntegerField(default=1)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leverages', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
