# Generated by Django 5.2.6 on 2025-11-20 23:58

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0004_rename_testnet_tradinguser_demo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Leverages',
            new_name='Leverage',
        ),
        migrations.AlterModelOptions(
            name='leverage',
            options={'verbose_name': 'Leverage', 'verbose_name_plural': 'Leverages'},
        ),
    ]
