# Generated by Django 5.2.6 on 2025-11-21 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0005_rename_leverages_leverage_alter_leverage_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradinguser',
            name='api_key_demo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tradinguser',
            name='api_secret_demo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
