# Generated by Django 5.2.6 on 2025-11-22 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0006_tradinguser_api_key_demo_tradinguser_api_secret_demo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tradinguser',
            name='api_key_demo',
        ),
        migrations.RemoveField(
            model_name='tradinguser',
            name='api_secret_demo',
        ),
    ]
